management:
  context-path: /admin
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    
---
spring:
  profiles: lattice-local
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.11.11}
    username: ${RABBITMQ_USERNAME:sclark}
    password: ${RABBITMQ_PASSWORD:test123}
eureka:
  client:
    service-url:
      defaultZone: http://service-registry.local.lattice.cf/eureka/
  instance:
    hostname: ${CF_INSTANCE_IP:localhost}
    nonSecurePort: ${CF_INSTANCE_PORT:${PORT:${server.port:8080}}}
    securePortEnabled: false
    
---
spring:
  profiles: lattice-aws
  rabbitmq:
    host: ${RABBITMQ_HOST:52.20.207.103.xip.io}
    username: ${RABBITMQ_USERNAME:sclark}
    password: ${RABBITMQ_PASSWORD:test123}
eureka:
  client:
    service-url:
      defaultZone: http://service-registry.52.20.207.103.xip.io/eureka/
  instance:
    hostname: ${CF_INSTANCE_IP:localhost}
    nonSecurePort: ${CF_INSTANCE_PORT:${PORT:${server.port:8080}}}
    securePortEnabled: false